### ISSUE TITLE
Improvements to Downloads page

### ISSUE THREAD

**Issue by zoffixznet** [Raku/raku.org#114]
Filing this, since I can't deliver within promised deadlines, and we might need improved Downloads page sooner.

----------

The improvements to the Downloads page were discussed in Issues https://github.com/perl6/perl6.org/issues/96 and https://github.com/perl6/perl6.org/issues/109

The original plan was me working on the BootStrap 4 de-bittrotting and conversion of the site to a web app and would also include some content updates, which would include improvements to the Downloads page.

While I hope to eventually finish that work, with the French lessons I started taking, newly signed up to the gym, and the TPF grant, I have a lot less free time than I used to and this work might not come to fruition for a few more months.

However, Learning Perl 6 will be published fairly soon (author is giving the book to O'Rly on June 18th, 2018 + however long it takes them to process the remaining stuff). I've seen a bunch of people say they're waiting for that book before they start with Perl 6, so I foresee an influx of new users when the book comes out and it'd be nice to offer the best experience in obtaining a copy of Perl 6 for them.

-----------

So, what I'm saying is if anyone had plans for a better Downloads page, go with them. Don't wait for me to finish the site update.

**Comment by coke** [comment]
Closing this out - thanks for the effort.
