### ISSUE TITLE
Nothing obvious links to github

### ISSUE THREAD

**Issue by Altreus** [Raku/raku.org#123]
I expected a link, or several links, to github projects on either the homepage or downloads page. I didn't look any further to see whether these links existed anywhere else because even if they do they should be where I looked too.

There should definitely be a link to the source code of the site itself (i.e. this repo), and probably a link to rakudo on the page that tells you how to install rakudo. Other links might be appropriate elsewhere.

**Comment by JJ** [comment]
Makes sense.

**Comment by 2colours** [comment]
Absolutely. I still discover new Raku repositories to this day (after one year and a half) - no surprise they are dead if you can't just come across them naturally.

**Comment by coke** [comment]
Fixed with f846942, thanks for the suggestion.
