### ISSUE TITLE
Raku examples link returns 502 from home page and resources page

### ISSUE THREAD

**Issue by StuartJMackintosh** [Raku/raku.org#140]
On the Raku home page (https://www.raku.org/), the "More..." -> 'Want to see more' link points to https://examples.perl6.org/ and this seems to redirect to https://examples.p6c.dev/ which returns "502 Bad Gateway"

file: https://github.com/Raku/raku.org/blob/master/source/index.html
Line 135: <a href="https://examples.perl6.org/"

Also on https://www.raku.org/resources/
Code Examples section:   Raku Examples, lots of example programs written in Raku

I wasn't able to (quickly) find the examples page therefore didn't offer a PR.

**Comment by Altai-man** [comment]
I think, firstly we need to ensure raku-examples repo can be rendered as static pages. The code is old pretty old and wants some refactoring, let's see if I'll be able to do it next weekend.

**Comment by rba** [comment]
examples.perl6.org was after he last years eastern server crash the first site took care of. That's the reason it's not on the same server as every other raku/perl6/rakudo website.

I had to restart it manually as it seems the mojo server did not come up properly after last reboot.

At the moment it's running again.

Overhauling the content is no issue for me. I have planned to dockerize it and the docker build needs to be automated as well.

Feedback is welcome.

**Comment by StuartJMackintosh** [comment]
Thanks for getting this going again. If you are working on content,suggest Perl 6 references are changed to Raku.

**Comment by StuartJMackintosh** [comment]
Will close this issue as the original report is now resolved.
