### ISSUE TITLE
MoarVM compilation fails on iSh/Alpine Linux in an iPad Air 3

### ISSUE THREAD

**Issue by Phiroc** [Raku/raku.org#143]
Hello,
I am trying to compile perl6/raku 2020.01 on iSh 1.0 (64) /Alpine Linux.
After about two hours of compilation, I get the following error:

_make: *** [Makefile: 365: gen/moar/stage1/NQPCORE.setting.moarvm] Error 1_

![IMG_0026](https://user-images.githubusercontent.com/7622719/75116663-0abefe80-566b-11ea-95da-919f6b35fbaf.png)

**Comment by JJ** [comment]
Probably not the place for this. You could try raising it in Rakudo, or since this is seems to be a MoarVM error, in MoarVM itself... 
Anyway, I wouldn't say it's an Alpine error. We have good working Alpine docker containers, after all. It's probably the processor architecture.

**Comment by Phiroc** [comment]
Thanks for you advice, JJ. Closing the issue.

**Comment by JJ** [comment]
But please open it somewhere else, it's a genuine issue and I'd love to
have it addressed; I also thanks you for taking the time to raise it.

**Comment by Phiroc** [comment]
JJ,
I created a MoarVM issue, as suggested. 
I am looking forward to running Raku on my iPad!
