### ISSUE TITLE
Smoke testing link in community page doesn't work

### ISSUE THREAD

**Issue by tqdv** [Raku/raku.org#148]
In the section "Smoke Testing" on the Community tab (https://raku.org/community/), there's a link to http://smoke.perl6.org/ which displays a default nginx page.

I assume the website is long gone. Should it be removed ? We could probably link to rakudist.raku.org in the future.

**Comment by coke** [comment]
This link was removed in 4b428c613803c01b5e5d28186f8f1fff31eadf1d in 2020.
