### ISSUE TITLE
No link/reference to LICENSE on raku homepage

### ISSUE THREAD

**Issue by finanalyst** [Raku/raku.org#154]
I was looking to see which license Raku is under and could not find a reference to it on the home page (raku.org)

A link at the bottom would be sufficient.

**Comment by coke** [comment]
I'd like to add a page with some text like:

> The raku development releases the specification and compilers they develop under the Artistic 2.0 license [link to opensource.org's page](https://opensource.org/license/artistic-2-0/).

> The broader development community is of course not required to use this license, but there is a large uptake among the development community.

**Comment by coke** [comment]
Doesn't have to be a separate page, can be a panel on an existing page.

**Comment by coke** [comment]
license stats now on https://raku.land/stats
