### ISSUE TITLE
Add a list of companies using Raku

### ISSUE THREAD

**Issue by patrickbkr** [Raku/raku.org#155]
I propose we add a list of companies using Raku to the raku.org startpage. In spirit similar to what many other (commercial) websites do to. (e. g. [Jira](https://www.atlassian.com/software/jira), [Holiday API](https://holidayapi.com/), and many more)

Given we actually find enough companies (I aim for at least 5), this can help to communicate that Raku is mature enough to be used in production and does have a userbase. This supports the follower effect: "If others use Raku it can't be that bad."

This ticket doubles as a call for companies using Raku and are willing to allow us to list them as using Raku on our frontpage.
So: If you work at a company that uses Raku, please do ask for permission in your company and speak up in this ticket.

There already are positive replies of:

- Edument
- Atikon

**Comment by zaucker** [comment]
Oetiker+Partner AG, www.oetiker.ch

**Comment by melezhik** [comment]
time to send resumes, huh? 😄

**Comment by patrickbkr** [comment]
HALTEC Hallensysteme GmbH (no linking)

**Comment by wtwt5237** [comment]
Tao Wang Lab/Quantitative Biomedical Research Center, UT Southwestern Medical Center

**Comment by scmorrison** [comment]
CNS Technical Group, Inc., cnstechgroup.com

**Comment by sztanyi** [comment]
Ping An Technology, https://tech.pingan.com/en/

**Comment by vedang** [comment]
Helpshift https://helpshift.com (we have some dev-tooling written in Raku)

**Comment by p6steve** [comment]
[Henley Cloud Consulting Ltd.](www.henleycloudconsulting.co.uk) using raku generally for provisioning and data migration scripts.

**Comment by patrickbkr** [comment]
@codesections Do you think the approvals in this ticket are sufficient to allow us to put the logos on our front page and not risk any legal trouble?

**Comment by lizmat** [comment]
Perhaps it would be an idea to just mention the names of the companies.  And give them the option of having their logo displayed when they sponsor the Raku project?  In whatever shape or form: could well be someone working there committing to the project  :-)

**Comment by coke** [comment]
I would be careful about setting up the page, especially with using logos if they weren’t provided for the express purpose. Also probably need language regarding the use of the company name Around implication of endorsement. Might be worth reaching out to the lawyer TPF is working with.

**Comment by patrickbkr** [comment]
@lizmat I don't think, that we currently have the reputation or number of visitors to be attractive for sponsors. On the other hand we need all the reputation we can get. So I think we shouldn't limit the effectiveness of our marketing by trying to sell sponsoring spots.

@coke Do you have respective contacts in TPF? Can you initiate the contact with the lawyer wrt this topic?

**Comment by coke** [comment]
I would go through the RSC for that, @patrickbkr .

**Comment by patrickbkr** [comment]
@coke Do you mean you will do so, or I should do so?

**Comment by coke** [comment]
Sorry for the confusion. I don’t have the contacts and I won’t be doing that work. I believe the RSC does and someone should ask them (but not me)

**Comment by vrurg** [comment]
I would say, whichever way we mention a company on the page, their permission should be asked in first place.

**Comment by patrickbkr** [comment]
@vrurg That was the idea of this ticket. The question is: Are the statements of the people in this ticket sufficient? coke proposed to forward this question to the TPF lawyer via the RSC. Would you be willing to initiate this contact?

**Comment by coke** [comment]
FYI, my concerns with using github comments as the means of approval is that we don't know that the folks making the post are able to speak for the company mentioned in this regard (esp. in regard to logos) and we also didn't have any specific text for them to be agreeing to.

**Comment by patrickbkr** [comment]
@vrurg or @niner (or whoever else is on the RSC) coke proposed to forward the question of how to best make sure we don't bring ourselves into legal trouble with company logos on the website to the TPF lawyer. Would one of you be willing to initiate this contact? Or tell me who I should contact if not the RSC?

**Comment by vrurg** [comment]
@patrickbkr I remember about the case, but can't get the right moment. Because if I start it I wanna be sure I will be able to have it done.

**Comment by vrurg** [comment]
It took much longer than I planned, but eventually I got a chance to discuss this matter with Nigel Hamilton. He suggests to add a disclaimer to the page footer saying that _'the trademarks are the property of their respective owners'_. Then a logo could be removed by a company request. If they have a problem with Raku we could try learning from them why is it so. Perhaps there is something we could improve get this kind of attitude fixed.

**Comment by patrickbkr** [comment]
I started putting together a PR with the respective changes to the raku.org website. I intend to put the logos on the website.

@wtwt5237 I think there is no logo of the Tao Wang Labs. Can we possibly just use the UT Southwestern logo (of which you are a subsidiary, if I understood correctly)? Alternatively, can I just [make up a logo](https://rooster.uber.space/patcloud/index.php/s/Fsixbfasc37eB4r/preview) for Tao Wang Labs?

@p6steve I [modified the logo](https://rooster.uber.space/patcloud/index.php/s/bpPrAYdmJAaoDWf/preview) I found on your companies website a little to be less longish. Are you fine with that?

@jnthn @niner @zaucker @wtwt5237 @scmorrison @vedang @p6steve Is there any problem with me just ripping the logos off the respective websites and possibly modifying them? (turning it grey or similar stylistic unifications to make them suitable for display on raku.org)

I will create a PR and add all of you as reviewers before this goes live in any case.

**Comment by wtwt5237** [comment]
@patrickbkr, you can use the QBRC logo on this page: https://github.com/jcao89757/TESSA (not sure how to attach a figure here). My lab is part of QBRC. You can modify that logo

**Comment by p6steve** [comment]
@patrickbkr - that's approved

**Comment by vedang** [comment]
Okay with us. Please use the "Helpshift Engineering" logo from
https://github.com/helpshift

/vedang
