### ISSUE TITLE
Raku®

### ISSUE THREAD

**Issue by coke** [Raku/raku.org#196]
The Raku® Programming Language is used in the footer. As I understand, this should be a trademark, not a registered mark.

**Comment by coke** [comment]
@codesections

**Comment by coke** [comment]
it appears in multiple locations

**Comment by codesections** [comment]
No, ® is fine for Raku – we needed to use ™ _before_ our trademark was registered, but it is now.  (The USPTO doesn't seem to believe in permalinks, but you can see the registration by using their [search page](https://tmsearch.uspto.gov/) and running a "structured search" for our registration number: `6456780`).

We should still use ™ for any marks that aren't registered (e.g., Rakudo, Camelia).  See #192.
