### ISSUE TITLE
Add links to companies?

### ISSUE THREAD

**Issue by coke** [Raku/raku.org#219]
We have several companies listed on the front page with just logos, and no links back to their sites.

Not sure if this was intentionally left out or not. @codesections ?

**Comment by patrickbkr** [comment]
I was the one responsible for those logos. As you suspected, those back links were left out intentionally. There was at least one company that was fine with their logo being there, but uncomfortable with the unknown consequences that a link might have. I.e. Would search engines start relating Raku to them?
