### ISSUE TITLE
Compilers: should we mention subclassing across the p5/p6 border?

### ISSUE THREAD

**Issue by timo** [Raku/raku.org#28]
On the right hand side of the Compilers page, there's a blurb about Inline::Perl5; it doesn't mention the possibility of subclassing at all. maybe it should, though.

**Comment by JJ** [comment]
Is this still relevant?

**Comment by coke** [comment]
@niner - any chance you could write a small blurb about this?

**Comment by coke** [comment]
Given the current state of Perl/Raku, I think the inline modules that are already referenced are fine and we don't need a lot of detail.
