### ISSUE TITLE
High ideals definition

### ISSUE THREAD

**Issue by smonff** [Raku/raku.org#36]
About this sentence in the homepage:

> Like her world-famous big sister, Perl 6 intends to carry forward the high ideals of the Perl community. 

It looks like that some people would be curious and would like to know more about these high ideals. Maybe [_high ideals_](http://somewhe.re) could point on a place where these things have already been said clearly.

**Comment by softmoth** [comment]
It could link to: http://www.perl.com/pub/1999/03/pm.html

**Comment by zoffixznet** [comment]
> It could link to: http://www.perl.com/pub/1999/03/pm.html
I'm :-1: on that for these reasons:

* It's a major case of tl;dr.
* It's from 1999, lauding Perl as a postmodern language, which feels a bit silly reading it in 2015.
* If you're not already a fan of Larry's witticism, the "highlights" are a bit weird and confusing, considering the user will had clicked on "high ideals of the Perl community" to get to the page.

**Comment by coke** [comment]
I appreciate the ask, but I'm going to close this out.
