### ISSUE TITLE
How to report bugs?

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/raku.org#61]
Apparently, when trying to find a right place to submit a bug report people may start from perl.org.

Seems like we should have a page with a list of bug trackers for every subproject. If there's already a page for this, we should just link to it.

This was mentioned in one of the comments on https://perl6advent.wordpress.com/2016/12/23/day-23-everything-is-either-wrong-or-less-than-awesome/

**Comment by coke** [comment]
Fixed with f846942, thanks for the suggestion
