### ISSUE TITLE
Remove reference to 6.0.0

### ISSUE THREAD

**Issue by coke** [Raku/raku.org#68]
https://perl6.org/specification/ has some paragraphs from SYN01 which refer to 6.0.0

Need to rework the NOTES section.

**Comment by 2colours** [comment]
This site still exists - but does anything link to it? Could it be removed altogether?

**Comment by 2colours** [comment]
Nevermind, it's the More button under Language Design 
![image](https://user-images.githubusercontent.com/37218286/201522379-493f4a52-d06a-4283-a40e-f18227705a8f.png)
