### ISSUE TITLE
Mention Matrix as an alternative to using webchat.freenode

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/raku.org#88]
Page in question: https://perl6.org/community/irc

I was reading [this](https://opensource.com/article/17/10/managing-casual-contributors) article and realized something. There are [not many](https://matrix.org/blog/wp-content/uploads/2017/07/Screen-Shot-2017-07-06-at-14.36.42-1024x780.png) matrix users right now, and I see only 10 users on perl6 channel. However, it's a great way to make people stay. Once you join a channel it won't leave automatically when you close your browser, in fact you'll stay forever online and you'll be getting messages that were sent while your devices were off.

The link will look like this: https://riot.im/app/#/room/#freenode_#perl6:matrix.org
And those who are using Riot through the browser will have to click one button to join the channel. Those who don't have an account will have to create it, but I think that by mentioning this we should only be focusing on those who already have it.

And those who use desktop or phone apps will have to click “Room directory” and type ``#perl6:freenode.org`` in there.

Assigning myself so that I won't forget about this issue. But please free to work on it.

**Comment by coke** [comment]
With freenode dead, going to close this out.
