### ISSUE TITLE
Add p6lert widget somewhere on home page

### ISSUE THREAD

**Issue by zoffixznet** [Raku/raku.org#91]
Would be nice if the home page would list a few [most recent p6lerts](https://alerts.perl6.org/) somewhere on the homepage. Since some new users might not know we have this service and this way they'd see it and subscribe.

The [p6lert API docs](https://alerts.perl6.org/api) already list [copy-pasteable code for a JS widget](https://alerts.perl6.org/api#widget)—just need to find a good place for it and maybe tweak the CSS for it to make it look nice.

**Comment by coke** [comment]
@lizmat , is p6lert still a thing?

**Comment by lizmat** [comment]
Certainly not by that name.  But we do have a repo of it somewhere, I believe.
